spring:
  main:
    banner-mode: off
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
  kafka:
    enabled: true
    producer:
      bootstrap-servers: "127.0.0.1:9092"
      key-serializer: org.apache.kafka.common.serialization.UUIDSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: "product-catalog-service"

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([%t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
  level:
    org.apache.kafka: ERROR
