spring:
  main:
    banner-mode: off
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
  kafka:
    enabled: true

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([%t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
  level:
    org.apache.kafka: ERROR
