spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:development"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  kafka:
    producer:
      bootstrap-servers: "127.0.0.1:9092"
      key-serializer: org.apache.kafka.common.serialization.UUIDSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: "product-catalog-service"
