name: "Continuous Integration"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3.3.0
      - name: "Set up JDK"
        uses: actions/setup-java@v3.9.0
        with:
          java-version: "17"
          distribution: "corretto"
      - name: "Validate Gradle wrapper"
        uses: gradle/wrapper-validation-action@v1.0.5
      - name: "Run chmod to make gradlew executable"
        run: chmod +x ./gradlew
      - name: "Build with Gradle"
        uses: gradle/gradle-build-action@v2.3.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          arguments: build --scan
